language: node_js

node_js:
  - "11"

install:
  - npm install

before_script:
  - npm run config
  - npm run compile

script:
  - npm run test

deploy:
  - provider: script
    script: bash scripts/deploy_travis_ci.sh
    github_token: $GITHUB_TOKEN
    on:
      branch: master

after_success:
  - npm run test:coveralls